replicaCount: 1

releaseName: final-project

image:
  polyRepository: basharz/poly
  polyTag: "2.1"
  yoloRepository: basharz/yolo
  yoloTag: "2.1"

polyPort: 8443
yoloPort: 8441

service:
  port: 80

ingress:
  name: ingress-hosts
  host: basharz.atech-bot.click
  path: "/"
  tls: tls-secret-basharz

imagePullSecrets: dockerhub

maxSurge: 3

hpa:
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
