apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.releaseName }}-yolo-deployment
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.releaseName }}-yolo
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: {{ .Values.maxSurge }}
  template:
    metadata:
      labels:
        app: {{ .Values.releaseName }}-yolo
    spec:
      containers:
        - name: {{ .Values.releaseName }}-yolo
          image: {{ .Values.image.yoloRepository }}:{{ .Values.image.yoloTag }}
          env:
            - name: BUCKET_NAME
              value: "basharziv"
            - name: SQS_QUEUE_NAME
              value: "bashar_z_sqs"
            - name: LOAD_BALANCER
              value: "https://basharz.atech-bot.click"
            - name: DYNAMO_TABLE
              value: "bashar_ziv_aws"
          volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
              readOnly: true
          ports:
            - containerPort: {{ .Values.yoloPort }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
      volumes:
        - name: aws-credentials
          secret:
            secretName: aws-credentials
